### PR TITLE
CAP-293 Timeseries Notebooks

### PR DESCRIPTION
**Pull request by tomw66**
Finished up the two notebooks displaying basic timeseries with model data

### CODE REVIEW

**Review by crbunney — COMMENTED** [review]
Looks good

I don't know whether we need to worry about the warnings, or maybe suppress them if they can be ignored?

Also, could you explain what units the coordinates are in? They don't look like lat/lons

**Comment by tomw66** [comment]
I'm also in 2 minds about the warnings, think it can be ignored but worth checking. 
@bsherratt have you come across iris warnings like this?
`.conda/envs/cap-notebooks/lib/python3.8/site-packages/iris/coords.py:1979: UserWarning: Collapsing a non-contiguous coordinate. Metadata may not be fully descriptive for 'projection_y_coordinate'.
  warnings.warn(msg.format(self.name()))`

coordinates are just in meters, with the origin a random-seeming point off the lizard.

**Comment by bsherratt** [comment]
> @bsherratt have you come across iris warnings like this? `.conda/envs/cap-notebooks/lib/python3.8/site-packages/iris/coords.py:1979: UserWarning: Collapsing a non-contiguous coordinate. Metadata may not be fully descriptive for 'projection_y_coordinate'. warnings.warn(msg.format(self.name()))`

Yes, this happens when you use `cube.collapsed` (or similar aggregation) on a coordinate that does not have bounds.

Another option to ignoring the warning is adding bounds, either in the file or after loading:
```
>>> coord = DimCoord([250000, 251000], units="m", standard_name="projection_x_coordinate")
>>> coord.has_bounds()
False
>>> coord.guess_bounds()
>>> coord.has_bounds()
True
>>> coord.bounds
array([[249500., 250500.],
       [250500., 251500.]])
```

**Comment by tomw66** [comment]
Thanks @bsherratt !

I think we can leave warnings as-is for now, may come back to it if flagged as an issue.

**Review by crbunney — DISMISSED** [review]

**Comment by lucascatherine** [comment]
Hi Tom, 
 Could you include a bit more in the intro about what linear interpolation actually is to make it clear how the timeseries is being implemented. This  just has to be a one line summary or a documentation link eg: for linear interpolation, perhaps say something alone lines of ... 
 
 'Using Linear interpolation will provide a time series of data values at a single given point in space, defaulting to ground level for altitude. Linear polynomials are used to construct new data points within the range of a discrete set of known data points.'

Then have a similar explanation for the Spatial interpolation one too just to make it clearer.

**Comment by tomw66** [comment]
@lucascatherine Have added a few lines

**Pull request merged**
