### PR TITLE
added notebook for displaying boundaries

### PR DESCRIPTION
**Pull request by tomw66**

### CODE REVIEW

**Comment by lucascatherine** [comment]
Great Stuff, looks fab. Just a couple of things. the comment 'This notebook will show you how to display boundaries for regions, LSOA, MSOA, etc on an interactive map.' ..can you change to 'This notebook will show you how to display boundaries for regions on an interactive map.. To display  LSOA, MSOA, use the appropriate input file'. ( Ideally this would then link to some documentation on the shapefiles we currently have available. This currently documented in https://metoffice.atlassian.net/wiki/spaces/AD/pages/3643310095/Requirements+list+for+location+time+periods+calculations+data so perhaps link to there for now until we have something better .)   Also  'Take a look and play around with it a bit.' is unnecessary. Can you just remove this line.

**Comment by tomw66** [comment]
Have corrected as suggested @lucascatherine @crbunney

**Comment by lucascatherine** [comment]
Thanks Tom. This looks all good to me now. Is fine to merge. Only caveat is once we have a proper help guide for the ONS boundary files used we will need to update the link in the notebook to reflect this. I will raise a JIRA ticket to come back to for this.
JIRA ticket below:

https://metoffice.atlassian.net/browse/CAP-342?atlOrigin=eyJpIjoiMGIyNGViYzMxODk5NDA4Nzk5NWUwMDM2NzAyM2M4OWUiLCJwIjoiaiJ9

**Review by crbunney — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
